import { createElement } from 'lwc';
import GCX_Messaging_Service from 'c/gCX_Messaging_Service';

describe('c-g-c-x-messaging-service', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-g-c-x-messaging-service', {
            is: GCX_Messaging_Service
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});