import { createElement } from 'lwc';
import GCX_Interaction_Controls from 'c/gCX_Interaction_Controls';

describe('c-g-c-x-interaction-controls', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-g-c-x-interaction-controls', {
            is: GCX_Interaction_Controls
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});